name: CI-ru

on:
  push:
    branches: [main-ru, "feature.*"]
  pull_request:

env:
  RUBY_VERSION: 2.5.3
  NODE_VERSION: 16

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - run: bundle install & bundle exec rake sass:import & bundle exec middleman build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: sass-lang.su
          allow_empty_commit: true
